
/**
Constructor
Do not call Function in Constructor.
*/
class TabView()
{
	super();

	//TODO:edit here

}
extends AView;


function TabView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function TabView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function TabView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here
	
};

function TabView*setData(data)
{
	console.log("setData: ", data);
};